# Generated by Django 4.2.6 on 2023-10-30 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=500)),
                ('Email', models.EmailField(max_length=500, unique=True)),
                ('Password', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Data',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Label', models.CharField(max_length=500)),
                ('DateCreated', models.DateField()),
                ('UserID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='UserApp.users')),
            ],
        ),
    ]
