# Generated by Django 4.2.6 on 2023-10-30 13:36

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='DateCreated',
        ),
        migrations.AddField(
            model_name='data',
            name='DateCraeted',
            field=models.DateField(auto_now_add=True, db_column='date_created', default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='data',
            name='ID',
            field=models.AutoField(db_column='id', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='data',
            name='Label',
            field=models.CharField(db_column='label', max_length=500),
        ),
        migrations.AlterField(
            model_name='data',
            name='UserID',
            field=models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='UserApp.users'),
        ),
        migrations.AlterField(
            model_name='users',
            name='Email',
            field=models.EmailField(db_column='email', max_length=500, unique=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='ID',
            field=models.AutoField(db_column='id', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='users',
            name='Name',
            field=models.CharField(db_column='name', max_length=500),
        ),
        migrations.AlterField(
            model_name='users',
            name='Password',
            field=models.CharField(db_column='password', max_length=500),
        ),
    ]
