# Generated by Django 4.2.6 on 2023-10-31 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0002_remove_data_datecreated_data_datecraeted_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Data',
        ),
    ]
