# Generated by Django 4.2.6 on 2023-10-31 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0003_delete_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('ID', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('Label', models.CharField(db_column='label', max_length=500)),
                ('DateCraeted', models.DateField(auto_now_add=True, db_column='date_created')),
                ('UserID', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='UserApp.users')),
            ],
        ),
    ]
