# Generated by Django 4.2.6 on 2023-10-31 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0006_remove_data_user_id_users_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='data',
            field=models.ManyToManyField(blank=True, related_name='users', to='UserApp.data'),
        ),
    ]
