# Generated by Django 4.2.6 on 2023-10-31 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0007_alter_users_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='data',
        ),
        migrations.AddField(
            model_name='data',
            name='user_id',
            field=models.ForeignKey(db_column='user_id', default=1, on_delete=django.db.models.deletion.CASCADE, to='UserApp.users'),
            preserve_default=False,
        ),
    ]
