# Generated by Django 4.2.6 on 2023-11-03 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0010_alter_data_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='sound_uri',
            field=models.TextField(db_column='sound_uri', default=1),
            preserve_default=False,
        ),
    ]
