# Generated by Django 4.2.6 on 2023-11-03 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0012_soundupload'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SoundUpload',
        ),
    ]
